run_directory:
	../../25/scripts/preprocess.sh skj grid16

clean:
	rm -rfv grid16skj
	rm -fv *.eps
	rm -fv *.log
	rm -fv *.ifr
	rm -fv *.pos
	rm -fv *.tag
	rm -fv *.par
	rm -fv *.p000
	rm -fv *.log
	rm -fv *.ifr
	rm -fv *.tag
	rm -fv *.gmt
	rm -fv gmt.*
	rm -fv variance
	rm -fv *_regions.dat
	rm -fv *_domain.dat
	rm -fv *_region_numbers.dat
	rm -rv *.cst
