//$Id: pattdisp.h 2754 2011-01-02 20:57:07Z jsibert $
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pattdisp */

#ifndef _Included_pattdisp
#define _Included_pattdisp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pattdisp
 * Method:    runNative
 * Signature: ([C[C)V
 */
JNIEXPORT void JNICALL Java_pattdisp_runNative
  (JNIEnv *, jobject, jcharArray, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
