#!/bin/bash
if [ $# -lt 1 ]; then
   echo "Usage: gridmap prnfile"
   echo "       for example, gridmap skj26"
   exit 0
fi

REGION=-R110/215/-45/25
#REGION=-R115/170/-15/15
#REGION=-R110/200/-25/20
#REGION=-R130/170/-15/10
echo $REGION
PROJECTION=-JM6i
echo $PROJECTION
MAP=$1
echo $MAP
EPS=$MAP.eps
echo $EPS
rm -v $EPS
rm -v $MAP.png

EEZ_COLOR=1P/0/0/255
WET_COLOR=194/241/253
DRY_COLOR=237/214/151
SHORELINE=154/139/98
REG_COLOR=0/128/0
DOM_COLOR=$REG_COLOR

#gmtset ANOT_FONT_SIZE_PRIMARY 12 BASEMAP_TYPE fancy PAPER_MEDIA letter+ PAGE_ORIENTATION portrait HEADER_FONT_SIZE 16 HEADER_FONT 1 MEASURE_UNIT inch PLOT_DEGREE_FORMAT dddF
gmt gmtset ANOT_FONT_SIZE_PRIMARY 12 BASEMAP_TYPE fancy PAGE_ORIENTATION landscape HEADER_FONT_SIZE 16 HEADER_FONT 1 MEASURE_UNIT inch PLOT_DEGREE_FORMAT dddF

# draw fancy base map with messy 1 deg grid
gmt psbasemap -B10f5g1:.$1: $REGION $PROJECTION -V    -K > $EPS
# draw fancy base map with messy 1/2 deg grid
# psbasemap -B10f5g0.5:.$1: $REGION $PROJECTION -V    -K > $EPS

#draw coastlines with wet and dry areas filled
#gmt pscoast $REGION $PROJECTION -Di -G$DRY_COLOR -W$SHORELINE -V -O    >> $EPS
gmt pscoast $REGION $PROJECTION -Di -G$DRY_COLOR  -Wfaint,$SHORELINE -V -O -K >> $EPS

#draw region boundaries
gmt psxy $1_regions.dat  $REGION $PROJECTION -Ap -Wthick,$REG_COLOR -V -O -K >> $EPS

#process the prn file to plot the landmask
#echo "prn2gmt.sh " ./$1".prn"
#~/movemod/25/scripts/prn2gmt.sh ./$1.prn | psxy $REGION $PROJECTION -Sc0.03125i -G$SHORELINE -V -O -K >> $EPS
#
##draw EEZs
##psxy /home/jsibert/movemod/SPC2011/scripts/eznew.asc    $REGION $PROJECTION -A -W$EEZ_COLOR -O -K >> $EPS
##psxy /home/jsibert/movemod/SPC2011/scripts/eznew_am.asc $REGION $PROJECTION -A -W$EEZ_COLOR -O -K >> $EPS
#
# process the .pos file to show shifting
#echo "./pos2gmt.sh " $1".pos"
#./pos2gmt.sh $1.pos | psxy $REGION $PROJECTION -A -Wred -V -O -K >> $EPS
#
#
# draw region numbers 
gmt pstext $1_region_numbers.dat $REGION $PROJECTION  -F+f,,$REG_COLOR -V -O -K >> $EPS
#
# draw domain boundary
gmt psxy $1_domain.dat  $REGION $PROJECTION -Ap -Wfat,$REG_COLOR -V -O    >> $EPS
#psxy $REGION $PROJECTION -Ap -L -Wfat,$REG_COLOR -V -O <<EOF   >> $EPS
#>
#115.00 -20.00
#115.00 15.00
#>
#195.00 15.00
#195.00 -20.00
#EOF



##draw coastlines with wet areas open (to cover up the ends of the region and EEZ boundaries)
##pscoast $REGION $PROJECTION -Di -G$DRY_COLOR  -W$SHORELINE -V -O      >> $EPS

#extract coastline data for gmt2cst
gmt pscoast $REGION $PROJECTION -Di -W > $MAP.gmt
#
#rm  -v .gmt*
gv $EPS &
#ps2raster -V -A -Tg -E300 $EPS
#eog $MAP.png &
