//$Id: banner.cpp 3127 2013-12-05 22:40:36Z jsibert $
#include <fvar.hpp>
#include <adstring.hpp>
#include <sstream>


//extern adstring copyright; ///< Text string containing copyright information; defined in the .tpl file

/*! \brief Generates a boast.
     Provides information on SVN revision number, compiler and operating system.
     Includes the file
     "banner-info.cpp" containg information generated by the makefile.
    \param program_name a adstring containing a version, e.g. "4.0x"
    \return an adstring containg the boast
 */
adstring make_banner(const adstring& program_name)
{
  #ifndef __APPLE__
  #include "banner-info.cpp"
  #endif

  std::ostringstream ss;
  ss << program_name;
  #ifndef __APPLE__
  ss << "\n  Source directory: " << wd;
  ss << "\n  SVN revision number: " << rev;
  #endif
  ss << "\n  Compiler: ";
  
#if defined(__GNUC__)
  ss <<  "Gnu C++" << __GNUC__ << '.' << __GNUC_MINOR__ << '.' << __GNUC_PATCHLEVEL__;
#else
   ss << "Unknown Compiler";
#endif

  #ifndef __APPLE__
  ss << " on " << host;
  ss << "\n  Architecture: " << 8*sizeof(void*) << " bits";
  ss << "\n  Operating system: " << os;
  if (which_library() == 'o')
     ss << "\n  Optimized ADMB libraries";
  else
     ss << "\n  Safe ADMB libraries";
  ss << ", Version " << admb_version << "\n";
  #endif
  ss << '\0';

  adstring s(ss.str().c_str());
  return(s);
}

/*
int main(void)
{
   cout << make_banner(__FILE__) << endl;
   return(0);
}
*/
